# _config.yml
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      mathjax: true
      comments: true
      sidebar:
        nav: "index"
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      mathjax: true
      comments: true
      sidebar:
        nav: "index"

# Make sure you have this:
navigation:
  main: main

title: "Mistakes Will Be Made"
subtitle: "Learning by doing things the wrong way."
description: "A website by Lucas Grigolato."
url: "https://lucasgrigolato.com"
baseurl: "" # leave empty for main site
repository: "grigosback/grigosback.github.io"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
minimal_mistakes_skin: "dark"

# Enable the top navigation bar
header:
  overlay_color: "#000"
  overlay_filter: "0.3"
  show_overlay_excerpt: false
  actions:
    - label: "Get in Touch"
      url: "/contact/"

# Author
author:
  name: "Lucas Grigolato"
  avatar: "/assets/images/profile.webp"
  bio: "Telecommunications Enginner / FPGA Engineer / Amateur Musician"
  location: "Noord Brabant, The Netherlands"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/grigosback"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/lucas-grigolato/"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:lucasmarianogrigolato@gmail.com"

# Plugins supported by GitHub Pages
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-archives

# Navigation bar (linked to _data/navigation.yml)
include: ["_pages"]

paginate: 5
paginate_path: "/blog/page:num/"
timezone: Europe/Amsterdam

# Breadcrumbs
breadcrumbs: true

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-SQN1062YXW"

# Comments
comments:
  provider: "giscus"
  giscus:
    repo: "grigosback/grigosback.github.io" # repository name
    repo_id: "R_kgDOP-Np9Q"                 # Get this from giscus.app
    category_name: "Comments"               # Create a category in GitHub Discussions and name it here
    category_id: "DIC_kwDOP-Np9c4C6IFv"     # Get this from giscus.app
    discussion_term: "pathname"
    strict: "0"
    reactions_enabled: "1"
    emit_metadata: "0"
    input_position: "bottom"
    theme: "transparent_dark" # since you use a dark skin
    lang: "en"
    loading: "lazy"
